services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: cinema
    ports:
      - 3306:3306
    volumes:
      - ./sql_data:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 1234
    depends_on:
      - db
    networks:
      - app-network
 
  web:
    build: .
    container_name: php_apache
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    